### ISSUE TITLE
Incorrect DATA_FILE_NAME  in prepare_alpaca.py script

### ISSUE THREAD

**Issue by lucas-ventura** [Lightning-AI/lit-llama#182]
Description: The prepare_alpaca.py script in the repository contains an error in the definition of the DATA_FILE_NAME variable. The current value is "[alpaca_data_cleaned.json](https://github.com/Lightning-AI/lit-llama/blob/main/scripts/prepare_alpaca.py#L17)", while it should be "alpaca_data_cleaned_archive.json". 

Suggested Solution:
Update the value of the DATA_FILE_NAME variable to "alpaca_data_cleaned_archive.json" in the prepare_alpaca.py script to match the actual filename.
```
DATA_FILE = "https://raw.githubusercontent.com/tloen/alpaca-lora/main/alpaca_data_cleaned_archive.json"
DATA_FILE_NAME = "alpaca_data_cleaned_archive.json"
```

**Comment by awaelchli** [comment]
They have previously renamed it from alpaca_data_cleaned to alpaca_data_cleaned_archive. For us the only thing that matters is that the URL is correct, since our scripts don't need to directly load this file but our preprocessed ones. Feel free to send a PR correcting the inconsistency if you are interested :)
