### ISSUE TITLE
Is it possible to train llama-lora with a single V100 32GB GPU? 

### ISSUE THREAD

**Issue by pangjh3** [Lightning-AI/lit-llama#204]
I re-vise the precision to "16-mixed",
and run in a single V100 32GB GPU, but suffer from the OOM problem.

Can anyone train the llama-lora in a single V100 GPU?

**Comment by awaelchli** [comment]
@pangjh3 Finetuneing with our LoRA script is definitely possible on a single GPU with > 24 GB. This is because the LoRA method reduces the number of trainable parameters significantly. 
Training from scratch with LoRA is not possible at the moment (LoRA has shown to be successful only for finetuning so far).

**Comment by awaelchli** [comment]
@pangjh3 Have you gotten a chance to try the lora-finetuning? Did it work with your V100?

**Comment by zzzhacker** [comment]
Yeah you can do lora-finetuning on V100. I did last week on my custom dataset.

**Comment by awaelchli** [comment]
Thanks for confirming @zzzhacker :)
