### ISSUE TITLE
The implementation of lit-llama-adapter is quite different from the original paper

### ISSUE THREAD

**Issue by slyviacassell** [Lightning-AI/lit-llama#263]
Refer to the [original paper](https://arxiv.org/abs/2303.16199) and [implementation,](https://github.com/ZrrSkywalker/LLaMA-Adapter/blob/fd4fb6cb8f947c941c5ec3b9dd6342b4a06ed727/alpaca_finetuning_v1/llama/model.py#L101-L108) LLaMA-Adapter concatenate the learnable prompt with other tokens. However, the [implementation in this repository](https://github.com/Lightning-AI/lit-llama/blob/827f01b5a7235c26f16559ddda5b8733a1a7abf0/lit_llama/adapter.py#L82-L92) is different from the it. Are the two implementations equivalent?  

The lit-llama-adapter:
> https://github.com/Lightning-AI/lit-llama/blob/827f01b5a7235c26f16559ddda5b8733a1a7abf0/lit_llama/adapter.py#L82-L92

Original LLaMA-Adapter:
> https://github.com/ZrrSkywalker/LLaMA-Adapter/blob/fd4fb6cb8f947c941c5ec3b9dd6342b4a06ed727/alpaca_finetuning_v1/llama/model.py#L101-L108

**Comment by awaelchli** [comment]
@slyviacassell Ours is a rewrite of the paper yes, because ours needed to have a different license than the original code. Note that since we added our implementation in lit-llama, the original code was updated several times already. At the time we were re-implementing ours, the repo only had this implementation: https://github.com/ZrrSkywalker/LLaMA-Adapter/blob/fd4fb6cb8f947c941c5ec3b9dd6342b4a06ed727/llama/model.py

Since then, they created a separate model for finetuning on alpaca and added this into the v1 folder.

**Comment by slyviacassell** [comment]
@awaelchli Thanks for your timely reply. I have dived into the math expressions, and I found that these two implementations are equivalent. But I wonder to know whether there are performance differences?

**Comment by awaelchli** [comment]
There might be slight differences in performance yes. But I haven't noticed any significant deviation from my experiments finetuning on alpaca compared to the time they have reported in the paper (less than 1h with 8 GPUs).

**Comment by slyviacassell** [comment]
Thanks a lot! I'll try it latter.

**Comment by Andrei-Aksionov** [comment]
Hello @awaelchli 👋 
I didn't quite get it: current implementation in `Lit-LLaMa` uses summation instead of concatination because in this way it was implemented in the original implementation at the time you were rewriting the code?
I see that in the original repo there is `v2` where summation is used. But I can't figure out why there is such a deviation from the paper.

**Comment by awaelchli** [comment]
Hey @Andrei-Aksionov 
If you see deviations like these from the paper in the original code (I assume you are talking about [this](https://github.com/ZrrSkywalker/LLaMA-Adapter/blob/main/llama_adapter_v2_chat65b/llama/model.py)), it is best to ask the authors directly on their GitHub, but the way I see it is that it is equivalent, in the sense that it is just a mathematical rewrite of the formula combined with the attention and thus the code is different as well.
When writing adapter v1, I have verified numerically that the implementations are correct but this also follows if you write out the equations (3)-(7) from the paper https://arxiv.org/pdf/2303.16199.pdf together with the attention matrices.

**Comment by Andrei-Aksionov** [comment]
@awaelchli Thanks for the answer 🤜

**Comment by rasbt** [comment]
Oh interesting! As we discussed a few days ago, it might be interesting to explore whether we can use [torch.nn.functional.scaled_dot_product_attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) as well to simplify the code base @awaelchli & @lantiga

**Comment by carmocca** [comment]
@rasbt we do already! https://github.com/Lightning-AI/lit-llama/blob/main/lit_llama/model.py#L228

**Comment by rasbt** [comment]
Oops, sorry, you are right! I think I mixed up projects.
