### ISSUE TITLE
Where is the log saved?

### ISSUE THREAD

**Issue by ForcewithMe66** [Lightning-AI/lit-llama#369]
I can see that 
```
            fabric.log_dict(
                {"iter": iter_num, "train_loss": loss, "step": step_count, "lr": lr}
            )
            fabric.print(
                    f"iter {iter_num}: loss {loss.item():.4f}, time: {dt*1000:.2f}ms, speed: {tokens_sec_str} toks/s/device"
            )
```
But I can't find the log. Should I set the direction the log will be saved? How can I set it?

**Comment by awaelchli** [comment]
Hi @ForcewithMe66 Right now we are mostly only printing things because the scripts are quite simple. For adding more detailed logging via TensorBoard for exmaple, you could add a logger to Fabric. Here is the docs for logging: https://lightning.ai/docs/fabric/stable/guide/logging.html

So basically, if you add
```
from lightning.fabric.loggers import TensorBoardLogger

logger = TensorBoardLogger(root_dir="logs")
fabric = Fabric(loggers=logger)
```
to the scripts you will find some extra files in the logs dir and can run `tensorboard --logdir logs`.

**Comment by ForcewithMe66** [comment]
Thank you
