### ISSUE TITLE
Why does convert_checkpoint.py file doubles the model size from 13GB to 26GB for 7b LlaMa model?

### ISSUE THREAD

**Issue by mriganktiwari** [Lightning-AI/lit-llama#414]
I downloaded the LlaMa 7b model form "pyllama" which shows 13Gb disk space, but when converting for compatibility with "lit-llama" it shows 26GB of disk space.

Kindly help with the reason.

**Comment by carmocca** [comment]
It's because our conversion script converts it to `torch.float` precision: https://github.com/Lightning-AI/lit-llama/blob/main/scripts/convert_hf_checkpoint.py#L25

I don't know why we do this, it seems wasteful and a silent difference from what's in huggingface. Should we change this so the dtype is not changed by default @lantiga? You made this change in https://github.com/Lightning-AI/lit-llama/commit/15d5eeee05eaf4756f665c6990b0295edc9785b9#diff-44726afca71fd2f8b6c4baaf854adeba086152d27101ce7fd72469101a9cba81R22.

This issue is also present in lit-gpt

**Comment by lantiga** [comment]
Definitely @carmocca let's preserve the `dtype`

**Comment by mriganktiwari** [comment]
Thanks for clarification.
