### ISSUE TITLE
How can I run it using Hugging Face models?

### ISSUE THREAD

**Issue by kadirnar** [Lightning-AI/lit-llama#64]
Model: https://huggingface.co/decapoda-research/llama-7b-hf

**Comment by awaelchli** [comment]
Hey @kadirnar 
You mean using the huggingface weights and load them into our model? This is theoretically possible, but one would have to write a function that remaps the state keys in the checkpoints to our format (and probably reshape/rearrange the tensors). In addition, since the hf model is also split across multiple files, you would have to merge them. So not a straightforward answer sorry :) We could think about providing such a conversion function for the short term if that's desired. I think that in long term though, our goal of the project is not to rely on the pretrained weights due to license restrictions.

**Comment by lantiga** [comment]
I agree @awaelchli. To be practical, since I'm seeing people jumping on that checkpoint (before Meta takes it down 😅) we should provide a conversion script. Anyone wants to volunteer?

**Comment by kadirnar** [comment]
@patrickvonplaten @osanseviero @julien-c

Can you look at this?

**Comment by lantiga** [comment]
Looking into this @kadirnar

**Comment by kadirnar** [comment]
> Looking into this @kadirnar

Thank you. Can you update the readme file? Can you explain step by step?
