### ISSUE TITLE
Vocabulary size when training the tokenizer

### ISSUE THREAD

**Issue by kno10** [Lightning-AI/lit-llama#68]
For all I can tell, this will likely use the sentencepiece defaults (i.e., 8000 tokens vocabulary size) whereas Llama was supposedly trained using a vocabulary size of 32000?

https://github.com/Lightning-AI/lit-llama/blob/ba505cb18f66f7aa76bcef8520b9d45d8a145376/lit_llama/tokenizer.py#L46-L49

My suggestion is to
- [ ] add a parameter to set the vocabulary size
- [ ] set the default value to 32000 to match Llama?

**Comment by lantiga** [comment]
Good point, in the tests we are loading the tokenizer from the checkpoint, but one should be able to set it from there as well.

Thanks, doing that rn

**Comment by awaelchli** [comment]
Yes we could add that parameter. Note that we haven't actually used this train() function for llama, it is just there for the train.py skeleton script which for now runs on shakespeare, and tokenizer.train() is applied to that data. For the large amount of data that llama requires, one could anyway not feed all of it to this train() function. Just an FYI but otherwise the suggestion sounds good

**Comment by kno10** [comment]
Fair enough - I'd assume that it makes more sense to pre-train the tokenizer independently anyway (on a manual sample of suitable size).

**Comment by lantiga** [comment]
Done! Yes for Shakespeare I set it to a lower number explicitly. Thanks for opening the issue @kno10
