### ISSUE TITLE
Saving FSDP Model

### ISSUE THREAD

**Issue by ricardorei** [Lightning-AI/lit-llama#88]
I was trying to change the fine-tuning to use FSDP training but currently there is any way to save the checkpoint.

Saving in [train.py](https://github.com/Lightning-AI/lit-llama/blob/main/train.py#L93) is commented and the saving in [finetune.pt](https://github.com/Lightning-AI/lit-llama/blob/ac83160ecaf9e0e55e0cb8fdbbd466d774c0a2f8/lit_llama/lora.py#L162) only supports Lora. 

I am trying to compare full fine-tuning with Lora. For full fine-tuning using FSDP my checkpoint is saved with the embedding layer and lm_head in a single `flat_param` which prevents me to load the checkpoint afterwards. How can I recover the original model architecture and load that checkpoint into a single GPU for inference ?

**Comment by awaelchli** [comment]
Hey @ricardorei 
Right, it is commented out because for FSDP, we would normally only save a shard per process. For inference on a single device, it would require consolidating these states. I can look into this.

**Comment by DuarteMRAlves** [comment]
Hello, I have the following solution for this:

```python
from torch.distributed.fsdp.fully_sharded_data_parallel import (
    FullyShardedDataParallel as FSDP,
    FullStateDictConfig,
    StateDictType
)
    ckpt_path = ckpt_dir / f"epoch_{epoch}_step_{step}.pt"
    save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
    with FSDP.state_dict_type(
        model._forward_module, StateDictType.FULL_STATE_DICT, save_policy
    ):
        cpu_state = model._forward_module.state_dict()
    if fabric.is_global_zero:
        torch.save(cpu_state, ckpt_path)
```

This happens because `_FabricModule.state_dict` calls the `state_dict` method on the `_original_module`, which is not wrapped by the `FSDP` wrapper, and the `with FSDP.state_dict_type(...)` expects the model wrapped by `FSDP` which is stored as `_forward_module`, as in the PyTorch [tutorial](https://pytorch.org/tutorials/intermediate/FSDP_adavnced_tutorial.html#model-checkpoint-saving-by-streaming-to-the-rank0-cpu).

**Comment by awaelchli** [comment]
@DuarteMRAlves Yes exactly. Fabric needs to complete this ticket for FSDP: https://github.com/Lightning-AI/lightning/issues/14816 so that fabric.save() works with the FSDP strategy and basically under the hood it would more or less have the code you showed, although probably often FULL_STATE_DICT won't work due to memory constraints. 

I think we should consider adding the boilerplate code to train.py in the meantime, and probably kick off save-load support in Fabric soon.
